version: "3.8"

services:
  serviciousuario:
    image: resy/serviciousuario:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: final-user
    ports:
      - "8082:8082"
    environment:
      - PORT=8082
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=appuser
      - DB_PASS=secret
      - DB_NAME=resydb
    depends_on:
      - postgres
    networks:
      - backend

  postgres:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=appuser
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=resydb
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - serviciousuario
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend:
    driver: bridge
